### ISSUE TITLE
Light/Dark Mode

### ISSUE THREAD

**Issue by windowslogic** [Noxyntious/SHitSHell#3]
This would be a cool option for people who would like this feature.

**Comment by Noxyntious** [comment]
idk how to implement this im bad at vb net

**Comment by windowslogic** [comment]
Okay, I'll find time to add it myself.

**Comment by Noxyntious** [comment]
nvm i kinda think i know how to implement it (i havent used vb net in YEARS forgive me)

**Comment by Noxyntious** [comment]
there i did it but im having trouble with registry values to store the value

**Comment by windowslogic** [comment]
Light/dark mode now works and loads what the user set at launch, no registry values required.
