### ISSUE TITLE
Icons are broken in repository so I had to replace them.

### ISSUE THREAD

**Issue by windowslogic** [Noxyntious/SHitSHell#6]
I will replace these with better icons. But just thought this was hilarious. https://cdn.windowslogic.co.uk/img/hl772qyx.png

**Comment by Noxyntious** [comment]
icons work just fine in the builds so idk why they arent in the project files (if thats what you mean)

**Comment by windowslogic** [comment]
I had to replace them with a placeholder for now.

**Comment by Noxyntious** [comment]
Fixed (hopefully!)
